version: '3.3'

services:
        frontend:
                build:
                        context: ./
                        dockerfile: ./frontend/Dockerfile
                command: ./frontend/run
                volumes:
                        - ./frontend:/frontend
                ports:
                        - 3001:3000
                depends_on:
                        - backend 

        backend:
                build:
                        context: ./
                        dockerfile: ./backend/Dockerfile                
                command: /start-reload.sh
                volumes:
                        - ./backend:/app
                environment:
                        PORT: 8000
                        VARIABLE_NAME: CSM_Backend
                ports:
                        - 8000:8000
                depends_on:
                        - db

        db:
                build: 
                        context: ./
                        dockerfile: ./db/Dockerfile
                restart: always
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: dev-password-123
                        POSTGRES_DB: CSM
